---
title: "Statistical Methods - Assignment 3"
author: "Michel Mooiweer (1866761) Thomas Webbers (2560695) Eirik Kultorp (2544992)"
date: "December 2016"
output: pdf_document
urlcolor: "blue"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn=-1)
```

# Theoretical exercises

## 4.1

    // todo

## 4.2 

    // todo

# R-Exercises

## 4.3

### a)

```{r 4.3a, echo=F}
dat=matrix(as.numeric(as.matrix(read.table("crimemale.txt"))[2:19,]),ncol=3)
age=dat[,1]
income=dat[,2]
crimes=dat[,3]

investigate_linear_correlation <- function(v1,v2,xlab,ylab){
  print(v1)
  print(v2)
  plot(v1,v2,xlab=xlab,ylab=ylab)
  corr=cor(v1,v2)
  print(paste("Correlation: (",xlab,",",ylab,")",corr))
  corr=abs(corr)
  
  # TODO adjust these thresholds based on statistical standards (if they exist) 
  
  if (corr<0.7) w ="unlikely"
  else if (corr<0.8) w = "plausible"
  else w="likely"
  print(paste("Linear correlation seems",w))
}

investigate_linear_correlation(age,crimes,"age","crimes")

```

### b)

```{r 4.3b, echo=F}
investigate_linear_correlation(income,crimes,"income","crimes")
```

### c)


```{r 4.3c, echo=F}
```

### d)

```{r 4.3d, echo=F}
```

### e)

```{r 4.3e, echo=F}
```

## 4.4

### a)

```{r 4.4a, echo=F}
```

### b)

```{r 4.4b, echo=F}
```

## 4.5

### a)

```{r 4.5a, echo=F}
```

### b)

```{r 4.5b, echo=F}
```


### c)

```{r 4.5c, echo=F}
```

# Appendix

## 4.3.a

```{r eval=FALSE, ref.label="4.3a"}
```

## 4.3.b

```{r eval=FALSE, ref.label="4.3b"}
```

## 4.3.c

```{r eval=FALSE, ref.label="4.3c"}
```

## 4.3.d

```{r eval=FALSE, ref.label="4.3d"}
```

## 4.3.e

```{r eval=FALSE, ref.label="4.3e"}
```

## 4.4.a

```{r eval=FALSE, ref.label="4.4a"}
```

## 4.4.b

```{r eval=FALSE, ref.label="4.4b"}
```

## 4.5.a

```{r eval=FALSE, ref.label="4.5a"}
```

## 4.5.b

```{r eval=FALSE, ref.label="4.5b"}
```

## 4.5.c

```{r eval=FALSE, ref.label="4.5c"}
```
